### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by mchrdk** [elnigno/aula-dk-picture-download#19]
When running the script in windows i get the following error with Python 3.11.7
Do you have any idea how to remediate? 
PS C:\git\aula-dk-picture-download> python .\aula_download_albums_with_tags.py --outputFolder c:\git\aula\ --cutoffDate 2024-01-01
(13, 'Permission denied')
Chrome cookies: error occured
Chromium cookies: not found
Opera cookies: not found
Opera GX cookies: not found
Brave cookies: not found
(13, 'Permission denied')
Edge cookies: error occured
Vivaldi cookies: not found
Firefox cookies: found
Safari cookies: not found
Parameters:
  outputDirectory: c:\git\aula\
  cutoffDate: 2024-01-01

Traceback (most recent call last):
  File "C:\git\aula-dk-picture-download\aula_download_albums_with_tags.py", line 248, in <module>
    main()
  File "C:\git\aula-dk-picture-download\aula_download_albums_with_tags.py", line 212, in main
    profiles = client.get_profiles()
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\git\test\aula-dk-picture-download\aulaclient.py", line 102, in get_profiles
    return response_profile['data']['profiles']
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by elnigno** [comment]
Did you login to aula using MitID?

**Comment by elnigno** [comment]
It might be because aula.dk is using a new API version (v19), I've just pushed a fix for that.

**Comment by mchrdk** [comment]
i just pulled the newest version, and it looks like you fixed it!
