### ISSUE TITLE
Make --tags optional

### ISSUE THREAD

**Issue by elnigno** [elnigno/aula-dk-picture-download#2]
Right now tags are a required parameter, but they don't need to be.
If there are no tags, all pictures in an album/post/thread should be downloaded.

**Comment by givtrah** [comment]
I've seen tags on less than 10% of all pictures, tags are extremely unreliable.

**Comment by elnigno** [comment]
You can add tags yourself, and that's how I keep track of my children's pictures and download only those. Nevertheless, they should be an optional parameter.
