### ISSUE TITLE
If no pictures / albums are found in messages, the program crashes

### ISSUE THREAD

**Issue by givtrah** [elnigno/aula-dk-picture-download#8]
Traceback (most recent call last):
  File "x", line 182, in <module>
    albumsToDownload += getAlbumsToDownloadFromMessages()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "x", line 107, in getAlbumsToDownloadFromMessages
    messages = messagesResponse['messages']
               ~~~~~~~~~~~~~~~~^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by givtrah** [comment]
This error still exists. I found out that it's due to "sensitive" messages.

If I'm logged in using MitID I get no errors, if I'm logged in using unilogin (where you cannot read sensitive messages) the error happens. I suggest adding that you must be logged in with MitID somewhere.

**Comment by elnigno** [comment]
Thanks a lot for investigating! I'll update the README.

**Comment by elnigno** [comment]
Closing.
The issue occurs when using unilogin and downloading images from messages marked as sensitive. Since this login method does not seem to support such messages, the recommendation is to use Mit ID instead. README has been updated.

**Comment by elnigno** [comment]
Closing.
The issue occurs when using unilogin and downloading images from messages marked as sensitive. Since this login method does not seem to support such messages, the recommendation is to use Mit ID instead. README has been updated.
